In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [2]:

import warnings
warnings.filterwarnings('ignore')

In [3]:
df = pd.read_csv('https://query.data.world/s/2flixt3ifiq4j43dr5is3u362jnugw')
df.head()

,STATE/UT,CRIME HEAD,2001,2002,2003,2004,2005,2006,2007,2008,2009,2010,2011,2012
0,ANDHRA PRADESH,INFANTICIDE,1,1,3,0,0,0,1,0,5,6,1,6
1,ARUNACHAL PRADESH,INFANTICIDE,0,0,0,0,0,0,0,0,0,0,0,0
2,ASSAM,INFANTICIDE,0,5,0,0,1,0,0,0,0,0,0,0
3,BIHAR,INFANTICIDE,0,0,0,0,2,0,2,2,0,2,5,2
4,CHHATTISGARH,INFANTICIDE,7,29,5,12,0,15,11,6,2,0,10,5

In [4]:
df['Total']=df.iloc[:,-12:].sum(axis=1)
df.head()

,STATE/UT,CRIME HEAD,2001,2002,2003,2004,2005,2006,2007,2008,2009,2010,2011,2012,Total
0,ANDHRA PRADESH,INFANTICIDE,1,1,3,0,0,0,1,0,5,6,1,6,24
1,ARUNACHAL PRADESH,INFANTICIDE,0,0,0,0,0,0,0,0,0,0,0,0,0
2,ASSAM,INFANTICIDE,0,5,0,0,1,0,0,0,0,0,0,0,6
3,BIHAR,INFANTICIDE,0,0,0,0,2,0,2,2,0,2,5,2,15
4,CHHATTISGARH,INFANTICIDE,7,29,5,12,0,15,11,6,2,0,10,5,102

In [5]:
df.drop(df.columns[[2,3,4,5,6,7,8,9,10,11,12,13]], axis = 1, inplace = True)
df.head()

            STATE/UT   CRIME HEAD  Total
0     ANDHRA PRADESH  INFANTICIDE     24
1  ARUNACHAL PRADESH  INFANTICIDE      0
2              ASSAM  INFANTICIDE      6
3              BIHAR  INFANTICIDE     15
4       CHHATTISGARH  INFANTICIDE    102

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 494 entries, 0 to 493
Data columns (total 3 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   STATE/UT    494 non-null    object
 1   CRIME HEAD  494 non-null    object
 2   Total       494 non-null    int64
dtypes: int64(1), object(2)
memory usage: 11.7+ KB

In [7]:
df['CRIME HEAD'].value_counts()

OTHER CRIMES AGAINST CHILDREN           38
FOETICIDE                               38
 TOTAL CRIMES AGAINST CHILDREN          38
SELLING OF GIRLS FOR PROSTITUTION       38
ABETMENT OF SUICIDE                     38
KIDNAPPING and ABDUCTION OF CHILDREN    38
PROCURATION OF MINOR GILRS              38
EXPOSURE AND ABANDONMENT                38
RAPE OF CHILDREN                        38
INFANTICIDE                             38
PROHIBITION OF CHILD MARRIAGE ACT       38
MURDER OF CHILDREN                      38
BUYING OF GIRLS FOR PROSTITUTION        38
Name: CRIME HEAD, dtype: int64

In [8]:

df['STATE/UT'].value_counts()

PUNJAB               13
GOA                  13
MADHYA PRADESH       13
UTTARAKHAND          13
NAGALAND             13
ARUNACHAL PRADESH    13
TOTAL (STATES)       13
TOTAL (ALL-INDIA)    13
TAMIL NADU           13
HARYANA              13
TRIPURA              13
SIKKIM               13
CHHATTISGARH         13
KARNATAKA            13
A & N ISLANDS        13
DAMAN & DIU          13
D & N HAVELI         13
HIMACHAL PRADESH     13
WEST BENGAL          13
MIZORAM              13
BIHAR                13
RAJASTHAN            13
MANIPUR              13
JHARKHAND            13
ASSAM                13
LAKSHADWEEP          13
ANDHRA PRADESH       13
GUJARAT              13
CHANDIGARH           13
TOTAL (UTs)          13
MEGHALAYA            13
KERALA               13
PUDUCHERRY           13
JAMMU & KASHMIR      13
ODISHA               13
MAHARASHTRA          13
DELHI                13
UTTAR PRADESH        13
Name: STATE/UT, dtype: int64

In [9]:
df_RAPE_OF_CHILDREN =df.loc[df['CRIME HEAD']=='RAPE OF CHILDREN']
df_RAPE_OF_CHILDREN

              STATE/UT        CRIME HEAD  Total
76      ANDHRA PRADESH  RAPE OF CHILDREN   5023
77   ARUNACHAL PRADESH  RAPE OF CHILDREN     96
78               ASSAM  RAPE OF CHILDREN    443
79               BIHAR  RAPE OF CHILDREN    692
80        CHHATTISGARH  RAPE OF CHILDREN   4391
81                 GOA  RAPE OF CHILDREN    309
82             GUJARAT  RAPE OF CHILDREN   1514
83             HARYANA  RAPE OF CHILDREN   1785
84    HIMACHAL PRADESH  RAPE OF CHILDREN    819
85     JAMMU & KASHMIR  RAPE OF CHILDREN     79
86           JHARKHAND  RAPE OF CHILDREN    313
87           KARNATAKA  RAPE OF CHILDREN   1019
88              KERALA  RAPE OF CHILDREN   3060
89      MADHYA PRADESH  RAPE OF CHILDREN  13688
90         MAHARASHTRA  RAPE OF CHILDREN   9757
91             MANIPUR  RAPE OF CHILDREN     47
92           MEGHALAYA  RAPE OF CHILDREN    346
93             MIZORAM  RAPE OF CHILDREN    281
94            NAGALAND  RAPE OF CHILDREN     35
95              ODISHA  RAPE OF CHILDREN    964
96              PUNJAB  RAPE OF CHILDREN   1597
97           RAJASTHAN  RAPE OF CHILDREN   2940
98              SIKKIM  RAPE OF CHILDREN    121
99          TAMIL NADU  RAPE OF CHILDREN   1841
100            TRIPURA  RAPE OF CHILDREN    474
101      UTTAR PRADESH  RAPE OF CHILDREN   9934
102        UTTARAKHAND  RAPE OF CHILDREN    236
103        WEST BENGAL  RAPE OF CHILDREN    794
104     TOTAL (STATES)  RAPE OF CHILDREN  62598
105      A & N ISLANDS  RAPE OF CHILDREN    110
106         CHANDIGARH  RAPE OF CHILDREN    170
107       D & N HAVELI  RAPE OF CHILDREN     14
108        DAMAN & DIU  RAPE OF CHILDREN     18
109              DELHI  RAPE OF CHILDREN   3796
110        LAKSHADWEEP  RAPE OF CHILDREN      0
111         PUDUCHERRY  RAPE OF CHILDREN     71
112        TOTAL (UTs)  RAPE OF CHILDREN   4179
113  TOTAL (ALL-INDIA)  RAPE OF CHILDREN  66777

In [10]:

df_KIDNAPPING=df.loc[df['CRIME HEAD']=='KIDNAPPING and ABDUCTION OF CHILDREN']
df_KIDNAPPING

              STATE/UT                            CRIME HEAD  Total
114     ANDHRA PRADESH  KIDNAPPING and ABDUCTION OF CHILDREN   6093
115  ARUNACHAL PRADESH  KIDNAPPING and ABDUCTION OF CHILDREN    105
116              ASSAM  KIDNAPPING and ABDUCTION OF CHILDREN    204
117              BIHAR  KIDNAPPING and ABDUCTION OF CHILDREN   8579
118       CHHATTISGARH  KIDNAPPING and ABDUCTION OF CHILDREN   1333
119                GOA  KIDNAPPING and ABDUCTION OF CHILDREN    160
120            GUJARAT  KIDNAPPING and ABDUCTION OF CHILDREN   5558
121            HARYANA  KIDNAPPING and ABDUCTION OF CHILDREN   1609
122   HIMACHAL PRADESH  KIDNAPPING and ABDUCTION OF CHILDREN    591
123    JAMMU & KASHMIR  KIDNAPPING and ABDUCTION OF CHILDREN    219
124          JHARKHAND  KIDNAPPING and ABDUCTION OF CHILDREN    245
125          KARNATAKA  KIDNAPPING and ABDUCTION OF CHILDREN    881
126             KERALA  KIDNAPPING and ABDUCTION OF CHILDREN   1012
127     MADHYA PRADESH  KIDNAPPING and ABDUCTION OF CHILDREN   4517
128        MAHARASHTRA  KIDNAPPING and ABDUCTION OF CHILDREN   7549
129            MANIPUR  KIDNAPPING and ABDUCTION OF CHILDREN    281
130          MEGHALAYA  KIDNAPPING and ABDUCTION OF CHILDREN     47
131            MIZORAM  KIDNAPPING and ABDUCTION OF CHILDREN      7
132           NAGALAND  KIDNAPPING and ABDUCTION OF CHILDREN     16
133             ODISHA  KIDNAPPING and ABDUCTION OF CHILDREN    402
134             PUNJAB  KIDNAPPING and ABDUCTION OF CHILDREN   2355
135          RAJASTHAN  KIDNAPPING and ABDUCTION OF CHILDREN   2952
136             SIKKIM  KIDNAPPING and ABDUCTION OF CHILDREN     32
137         TAMIL NADU  KIDNAPPING and ABDUCTION OF CHILDREN   2506
138            TRIPURA  KIDNAPPING and ABDUCTION OF CHILDREN    148
139      UTTAR PRADESH  KIDNAPPING and ABDUCTION OF CHILDREN  30625
140        UTTARAKHAND  KIDNAPPING and ABDUCTION OF CHILDREN    311
141        WEST BENGAL  KIDNAPPING and ABDUCTION OF CHILDREN   2626
142     TOTAL (STATES)  KIDNAPPING and ABDUCTION OF CHILDREN  80963
143      A & N ISLANDS  KIDNAPPING and ABDUCTION OF CHILDREN     55
144         CHANDIGARH  KIDNAPPING and ABDUCTION OF CHILDREN    292
145       D & N HAVELI  KIDNAPPING and ABDUCTION OF CHILDREN     78
146        DAMAN & DIU  KIDNAPPING and ABDUCTION OF CHILDREN      6
147              DELHI  KIDNAPPING and ABDUCTION OF CHILDREN   3464
148        LAKSHADWEEP  KIDNAPPING and ABDUCTION OF CHILDREN      0
149         PUDUCHERRY  KIDNAPPING and ABDUCTION OF CHILDREN    111
150        TOTAL (UTs)  KIDNAPPING and ABDUCTION OF CHILDREN   4006
151  TOTAL (ALL-INDIA)  KIDNAPPING and ABDUCTION OF CHILDREN  84969

In [11]:

df_CHILD_MARRIAGE =df.loc[df['CRIME HEAD']=='PROHIBITION OF CHILD MARRIAGE ACT']
df_CHILD_MARRIAGE

              STATE/UT                         CRIME HEAD  Total
380     ANDHRA PRADESH  PROHIBITION OF CHILD MARRIAGE ACT    309
381  ARUNACHAL PRADESH  PROHIBITION OF CHILD MARRIAGE ACT      0
382              ASSAM  PROHIBITION OF CHILD MARRIAGE ACT      8
383              BIHAR  PROHIBITION OF CHILD MARRIAGE ACT     94
384       CHHATTISGARH  PROHIBITION OF CHILD MARRIAGE ACT    273
385                GOA  PROHIBITION OF CHILD MARRIAGE ACT      4
386            GUJARAT  PROHIBITION OF CHILD MARRIAGE ACT    928
387            HARYANA  PROHIBITION OF CHILD MARRIAGE ACT    103
388   HIMACHAL PRADESH  PROHIBITION OF CHILD MARRIAGE ACT     53
389    JAMMU & KASHMIR  PROHIBITION OF CHILD MARRIAGE ACT      0
390          JHARKHAND  PROHIBITION OF CHILD MARRIAGE ACT      0
391          KARNATAKA  PROHIBITION OF CHILD MARRIAGE ACT    109
392             KERALA  PROHIBITION OF CHILD MARRIAGE ACT     46
393     MADHYA PRADESH  PROHIBITION OF CHILD MARRIAGE ACT    177
394        MAHARASHTRA  PROHIBITION OF CHILD MARRIAGE ACT    768
395            MANIPUR  PROHIBITION OF CHILD MARRIAGE ACT      0
396          MEGHALAYA  PROHIBITION OF CHILD MARRIAGE ACT      3
397            MIZORAM  PROHIBITION OF CHILD MARRIAGE ACT      0
398           NAGALAND  PROHIBITION OF CHILD MARRIAGE ACT      0
399             ODISHA  PROHIBITION OF CHILD MARRIAGE ACT     19
400             PUNJAB  PROHIBITION OF CHILD MARRIAGE ACT     70
401          RAJASTHAN  PROHIBITION OF CHILD MARRIAGE ACT    160
402             SIKKIM  PROHIBITION OF CHILD MARRIAGE ACT      0
403         TAMIL NADU  PROHIBITION OF CHILD MARRIAGE ACT     39
404            TRIPURA  PROHIBITION OF CHILD MARRIAGE ACT      2
405      UTTAR PRADESH  PROHIBITION OF CHILD MARRIAGE ACT    110
406        UTTARAKHAND  PROHIBITION OF CHILD MARRIAGE ACT      0
407        WEST BENGAL  PROHIBITION OF CHILD MARRIAGE ACT    156
408     TOTAL (STATES)  PROHIBITION OF CHILD MARRIAGE ACT   3431
409      A & N ISLANDS  PROHIBITION OF CHILD MARRIAGE ACT      7
410         CHANDIGARH  PROHIBITION OF CHILD MARRIAGE ACT     10
411       D & N HAVELI  PROHIBITION OF CHILD MARRIAGE ACT      0
412        DAMAN & DIU  PROHIBITION OF CHILD MARRIAGE ACT      0
413              DELHI  PROHIBITION OF CHILD MARRIAGE ACT     10
414        LAKSHADWEEP  PROHIBITION OF CHILD MARRIAGE ACT      0
415         PUDUCHERRY  PROHIBITION OF CHILD MARRIAGE ACT     13
416        TOTAL (UTs)  PROHIBITION OF CHILD MARRIAGE ACT     40
417  TOTAL (ALL-INDIA)  PROHIBITION OF CHILD MARRIAGE ACT   3471

In [12]:
df_MURDER_OF_CHILDREN =df.loc[df['CRIME HEAD']=='MURDER OF CHILDREN']
df_MURDER_OF_CHILDREN

             STATE/UT          CRIME HEAD  Total
38     ANDHRA PRADESH  MURDER OF CHILDREN   1126
39  ARUNACHAL PRADESH  MURDER OF CHILDREN      0
40              ASSAM  MURDER OF CHILDREN     79
41              BIHAR  MURDER OF CHILDREN   1573
42       CHHATTISGARH  MURDER OF CHILDREN    547
43                GOA  MURDER OF CHILDREN     35
44            GUJARAT  MURDER OF CHILDREN    689
45            HARYANA  MURDER OF CHILDREN    371
46   HIMACHAL PRADESH  MURDER OF CHILDREN     71
47    JAMMU & KASHMIR  MURDER OF CHILDREN     17
48          JHARKHAND  MURDER OF CHILDREN     58
49          KARNATAKA  MURDER OF CHILDREN    489
50             KERALA  MURDER OF CHILDREN    516
51     MADHYA PRADESH  MURDER OF CHILDREN   1913
52        MAHARASHTRA  MURDER OF CHILDREN   2656
53            MANIPUR  MURDER OF CHILDREN     26
54          MEGHALAYA  MURDER OF CHILDREN     26
55            MIZORAM  MURDER OF CHILDREN      5
56           NAGALAND  MURDER OF CHILDREN      7
57             ODISHA  MURDER OF CHILDREN    168
58             PUNJAB  MURDER OF CHILDREN    478
59          RAJASTHAN  MURDER OF CHILDREN    560
60             SIKKIM  MURDER OF CHILDREN     28
61         TAMIL NADU  MURDER OF CHILDREN    819
62            TRIPURA  MURDER OF CHILDREN    100
63      UTTAR PRADESH  MURDER OF CHILDREN   8006
64        UTTARAKHAND  MURDER OF CHILDREN    108
65        WEST BENGAL  MURDER OF CHILDREN    152
66     TOTAL (STATES)  MURDER OF CHILDREN  20623
67      A & N ISLANDS  MURDER OF CHILDREN     15
68         CHANDIGARH  MURDER OF CHILDREN     21
69       D & N HAVELI  MURDER OF CHILDREN      7
70        DAMAN & DIU  MURDER OF CHILDREN      4
71              DELHI  MURDER OF CHILDREN    598
72        LAKSHADWEEP  MURDER OF CHILDREN      1
73         PUDUCHERRY  MURDER OF CHILDREN      8
74        TOTAL (UTs)  MURDER OF CHILDREN    654
75  TOTAL (ALL-INDIA)  MURDER OF CHILDREN  21277

In [13]:
df_CRIMES_CHILDREN =df.loc[df['CRIME HEAD']=='OTHER CRIMES AGAINST CHILDREN']
df_CRIMES_CHILDREN

              STATE/UT                     CRIME HEAD  Total
418     ANDHRA PRADESH  OTHER CRIMES AGAINST CHILDREN   4726
419  ARUNACHAL PRADESH  OTHER CRIMES AGAINST CHILDREN      4
420              ASSAM  OTHER CRIMES AGAINST CHILDREN    489
421              BIHAR  OTHER CRIMES AGAINST CHILDREN    188
422       CHHATTISGARH  OTHER CRIMES AGAINST CHILDREN   8282
423                GOA  OTHER CRIMES AGAINST CHILDREN    345
424            GUJARAT  OTHER CRIMES AGAINST CHILDREN   3115
425            HARYANA  OTHER CRIMES AGAINST CHILDREN    730
426   HIMACHAL PRADESH  OTHER CRIMES AGAINST CHILDREN    424
427    JAMMU & KASHMIR  OTHER CRIMES AGAINST CHILDREN     30
428          JHARKHAND  OTHER CRIMES AGAINST CHILDREN    330
429          KARNATAKA  OTHER CRIMES AGAINST CHILDREN    352
430             KERALA  OTHER CRIMES AGAINST CHILDREN   3029
431     MADHYA PRADESH  OTHER CRIMES AGAINST CHILDREN  37048
432        MAHARASHTRA  OTHER CRIMES AGAINST CHILDREN  12650
433            MANIPUR  OTHER CRIMES AGAINST CHILDREN      2
434          MEGHALAYA  OTHER CRIMES AGAINST CHILDREN     19
435            MIZORAM  OTHER CRIMES AGAINST CHILDREN     41
436           NAGALAND  OTHER CRIMES AGAINST CHILDREN      0
437             ODISHA  OTHER CRIMES AGAINST CHILDREN    671
438             PUNJAB  OTHER CRIMES AGAINST CHILDREN    360
439          RAJASTHAN  OTHER CRIMES AGAINST CHILDREN    361
440             SIKKIM  OTHER CRIMES AGAINST CHILDREN     71
441         TAMIL NADU  OTHER CRIMES AGAINST CHILDREN    482
442            TRIPURA  OTHER CRIMES AGAINST CHILDREN    138
443      UTTAR PRADESH  OTHER CRIMES AGAINST CHILDREN   8901
444        UTTARAKHAND  OTHER CRIMES AGAINST CHILDREN     87
445        WEST BENGAL  OTHER CRIMES AGAINST CHILDREN    779
446     TOTAL (STATES)  OTHER CRIMES AGAINST CHILDREN  83654
447      A & N ISLANDS  OTHER CRIMES AGAINST CHILDREN    115
448         CHANDIGARH  OTHER CRIMES AGAINST CHILDREN    101
449       D & N HAVELI  OTHER CRIMES AGAINST CHILDREN      4
450        DAMAN & DIU  OTHER CRIMES AGAINST CHILDREN     16
451              DELHI  OTHER CRIMES AGAINST CHILDREN   2665
452        LAKSHADWEEP  OTHER CRIMES AGAINST CHILDREN      0
453         PUDUCHERRY  OTHER CRIMES AGAINST CHILDREN     37
454        TOTAL (UTs)  OTHER CRIMES AGAINST CHILDREN   2938
455  TOTAL (ALL-INDIA)  OTHER CRIMES AGAINST CHILDREN  86592

In [14]:

df_BUYING_GIRLS =df.loc[df['CRIME HEAD']=='BUYING OF GIRLS FOR PROSTITUTION']
df_BUYING_GIRLS

              STATE/UT                        CRIME HEAD  Total
304     ANDHRA PRADESH  BUYING OF GIRLS FOR PROSTITUTION     44
305  ARUNACHAL PRADESH  BUYING OF GIRLS FOR PROSTITUTION      0
306              ASSAM  BUYING OF GIRLS FOR PROSTITUTION      0
307              BIHAR  BUYING OF GIRLS FOR PROSTITUTION      7
308       CHHATTISGARH  BUYING OF GIRLS FOR PROSTITUTION      0
309                GOA  BUYING OF GIRLS FOR PROSTITUTION      0
310            GUJARAT  BUYING OF GIRLS FOR PROSTITUTION      0
311            HARYANA  BUYING OF GIRLS FOR PROSTITUTION      5
312   HIMACHAL PRADESH  BUYING OF GIRLS FOR PROSTITUTION      0
313    JAMMU & KASHMIR  BUYING OF GIRLS FOR PROSTITUTION      0
314          JHARKHAND  BUYING OF GIRLS FOR PROSTITUTION      9
315          KARNATAKA  BUYING OF GIRLS FOR PROSTITUTION      0
316             KERALA  BUYING OF GIRLS FOR PROSTITUTION      0
317     MADHYA PRADESH  BUYING OF GIRLS FOR PROSTITUTION      8
318        MAHARASHTRA  BUYING OF GIRLS FOR PROSTITUTION    331
319            MANIPUR  BUYING OF GIRLS FOR PROSTITUTION      0
320          MEGHALAYA  BUYING OF GIRLS FOR PROSTITUTION      0
321            MIZORAM  BUYING OF GIRLS FOR PROSTITUTION      0
322           NAGALAND  BUYING OF GIRLS FOR PROSTITUTION      0
323             ODISHA  BUYING OF GIRLS FOR PROSTITUTION      0
324             PUNJAB  BUYING OF GIRLS FOR PROSTITUTION      2
325          RAJASTHAN  BUYING OF GIRLS FOR PROSTITUTION      7
326             SIKKIM  BUYING OF GIRLS FOR PROSTITUTION      0
327         TAMIL NADU  BUYING OF GIRLS FOR PROSTITUTION      0
328            TRIPURA  BUYING OF GIRLS FOR PROSTITUTION      0
329      UTTAR PRADESH  BUYING OF GIRLS FOR PROSTITUTION     11
330        UTTARAKHAND  BUYING OF GIRLS FOR PROSTITUTION      0
331        WEST BENGAL  BUYING OF GIRLS FOR PROSTITUTION    127
332     TOTAL (STATES)  BUYING OF GIRLS FOR PROSTITUTION    551
333      A & N ISLANDS  BUYING OF GIRLS FOR PROSTITUTION      0
334         CHANDIGARH  BUYING OF GIRLS FOR PROSTITUTION      0
335       D & N HAVELI  BUYING OF GIRLS FOR PROSTITUTION      0
336        DAMAN & DIU  BUYING OF GIRLS FOR PROSTITUTION      0
337              DELHI  BUYING OF GIRLS FOR PROSTITUTION      4
338        LAKSHADWEEP  BUYING OF GIRLS FOR PROSTITUTION      0
339         PUDUCHERRY  BUYING OF GIRLS FOR PROSTITUTION      0
340        TOTAL (UTs)  BUYING OF GIRLS FOR PROSTITUTION      4
341  TOTAL (ALL-INDIA)  BUYING OF GIRLS FOR PROSTITUTION    555

In [15]:
df_FOETICIDE =df.loc[df['CRIME HEAD']=='FOETICIDE']
df_FOETICIDE

              STATE/UT CRIME HEAD  Total
152     ANDHRA PRADESH  FOETICIDE     13
153  ARUNACHAL PRADESH  FOETICIDE      0
154              ASSAM  FOETICIDE      2
155              BIHAR  FOETICIDE     20
156       CHHATTISGARH  FOETICIDE     58
157                GOA  FOETICIDE      0
158            GUJARAT  FOETICIDE     11
159            HARYANA  FOETICIDE     45
160   HIMACHAL PRADESH  FOETICIDE      9
161    JAMMU & KASHMIR  FOETICIDE      6
162          JHARKHAND  FOETICIDE     19
163          KARNATAKA  FOETICIDE      1
164             KERALA  FOETICIDE      4
165     MADHYA PRADESH  FOETICIDE    109
166        MAHARASHTRA  FOETICIDE    115
167            MANIPUR  FOETICIDE      0
168          MEGHALAYA  FOETICIDE      0
169            MIZORAM  FOETICIDE      0
170           NAGALAND  FOETICIDE      0
171             ODISHA  FOETICIDE      8
172             PUNJAB  FOETICIDE     66
173          RAJASTHAN  FOETICIDE     41
174             SIKKIM  FOETICIDE      2
175         TAMIL NADU  FOETICIDE      0
176            TRIPURA  FOETICIDE      0
177      UTTAR PRADESH  FOETICIDE     82
178        UTTARAKHAND  FOETICIDE      0
179        WEST BENGAL  FOETICIDE      1
180     TOTAL (STATES)  FOETICIDE    612
181      A & N ISLANDS  FOETICIDE      1
182         CHANDIGARH  FOETICIDE      0
183       D & N HAVELI  FOETICIDE      0
184        DAMAN & DIU  FOETICIDE      0
185              DELHI  FOETICIDE     45
186        LAKSHADWEEP  FOETICIDE      0
187         PUDUCHERRY  FOETICIDE      0
188        TOTAL (UTs)  FOETICIDE     46
189  TOTAL (ALL-INDIA)  FOETICIDE    658

In [16]:
df_INFANTICIDE=df.loc[df['CRIME HEAD']=='INFANTICIDE']
df_INFANTICIDE

             STATE/UT   CRIME HEAD  Total
0      ANDHRA PRADESH  INFANTICIDE     24
1   ARUNACHAL PRADESH  INFANTICIDE      0
2               ASSAM  INFANTICIDE      6
3               BIHAR  INFANTICIDE     15
4        CHHATTISGARH  INFANTICIDE    102
5                 GOA  INFANTICIDE      2
6             GUJARAT  INFANTICIDE     16
7             HARYANA  INFANTICIDE     10
8    HIMACHAL PRADESH  INFANTICIDE      3
9     JAMMU & KASHMIR  INFANTICIDE      1
10          JHARKHAND  INFANTICIDE      2
11          KARNATAKA  INFANTICIDE     18
12             KERALA  INFANTICIDE     10
13     MADHYA PRADESH  INFANTICIDE    105
14        MAHARASHTRA  INFANTICIDE     72
15            MANIPUR  INFANTICIDE      0
16          MEGHALAYA  INFANTICIDE      3
17            MIZORAM  INFANTICIDE      0
18           NAGALAND  INFANTICIDE      2
19             ODISHA  INFANTICIDE      4
20             PUNJAB  INFANTICIDE     39
21          RAJASTHAN  INFANTICIDE     21
22             SIKKIM  INFANTICIDE      4
23         TAMIL NADU  INFANTICIDE     57
24            TRIPURA  INFANTICIDE      0
25      UTTAR PRADESH  INFANTICIDE    552
26        UTTARAKHAND  INFANTICIDE      0
27        WEST BENGAL  INFANTICIDE      4
28     TOTAL (STATES)  INFANTICIDE   1072
29      A & N ISLANDS  INFANTICIDE      0
30         CHANDIGARH  INFANTICIDE      0
31       D & N HAVELI  INFANTICIDE      0
32        DAMAN & DIU  INFANTICIDE      0
33              DELHI  INFANTICIDE      5
34        LAKSHADWEEP  INFANTICIDE      0
35         PUDUCHERRY  INFANTICIDE      0
36        TOTAL (UTs)  INFANTICIDE      5
37  TOTAL (ALL-INDIA)  INFANTICIDE   1077

In [17]:
df_TOTAL_CRIMES=df.loc[df['CRIME HEAD']==' TOTAL CRIMES AGAINST CHILDREN']
df_TOTAL_CRIMES

              STATE/UT                      CRIME HEAD   Total
456     ANDHRA PRADESH   TOTAL CRIMES AGAINST CHILDREN   18396
457  ARUNACHAL PRADESH   TOTAL CRIMES AGAINST CHILDREN     205
458              ASSAM   TOTAL CRIMES AGAINST CHILDREN    1614
459              BIHAR   TOTAL CRIMES AGAINST CHILDREN   12036
460       CHHATTISGARH   TOTAL CRIMES AGAINST CHILDREN   15203
461                GOA   TOTAL CRIMES AGAINST CHILDREN     908
462            GUJARAT   TOTAL CRIMES AGAINST CHILDREN   12075
463            HARYANA   TOTAL CRIMES AGAINST CHILDREN    4719
464   HIMACHAL PRADESH   TOTAL CRIMES AGAINST CHILDREN    2027
465    JAMMU & KASHMIR   TOTAL CRIMES AGAINST CHILDREN     356
466          JHARKHAND   TOTAL CRIMES AGAINST CHILDREN    1247
467          KARNATAKA   TOTAL CRIMES AGAINST CHILDREN    2961
468             KERALA   TOTAL CRIMES AGAINST CHILDREN    7911
469     MADHYA PRADESH   TOTAL CRIMES AGAINST CHILDREN   58312
470        MAHARASHTRA   TOTAL CRIMES AGAINST CHILDREN   35351
471            MANIPUR   TOTAL CRIMES AGAINST CHILDREN     356
472          MEGHALAYA   TOTAL CRIMES AGAINST CHILDREN     445
473            MIZORAM   TOTAL CRIMES AGAINST CHILDREN     335
474           NAGALAND   TOTAL CRIMES AGAINST CHILDREN      60
475             ODISHA   TOTAL CRIMES AGAINST CHILDREN    2283
476             PUNJAB   TOTAL CRIMES AGAINST CHILDREN    5021
477          RAJASTHAN   TOTAL CRIMES AGAINST CHILDREN    7220
478             SIKKIM   TOTAL CRIMES AGAINST CHILDREN     260
479         TAMIL NADU   TOTAL CRIMES AGAINST CHILDREN    5828
480            TRIPURA   TOTAL CRIMES AGAINST CHILDREN     932
481      UTTAR PRADESH   TOTAL CRIMES AGAINST CHILDREN   58507
482        UTTARAKHAND   TOTAL CRIMES AGAINST CHILDREN     879
483        WEST BENGAL   TOTAL CRIMES AGAINST CHILDREN    6051
484     TOTAL (STATES)   TOTAL CRIMES AGAINST CHILDREN  261498
485      A & N ISLANDS   TOTAL CRIMES AGAINST CHILDREN     305
486         CHANDIGARH   TOTAL CRIMES AGAINST CHILDREN     625
487       D & N HAVELI   TOTAL CRIMES AGAINST CHILDREN     103
488        DAMAN & DIU   TOTAL CRIMES AGAINST CHILDREN      44
489              DELHI   TOTAL CRIMES AGAINST CHILDREN   10654
490        LAKSHADWEEP   TOTAL CRIMES AGAINST CHILDREN       1
491         PUDUCHERRY   TOTAL CRIMES AGAINST CHILDREN     245
492        TOTAL (UTs)   TOTAL CRIMES AGAINST CHILDREN   11977
493  TOTAL (ALL-INDIA)   TOTAL CRIMES AGAINST CHILDREN  273475

In [18]:
df_PROCURATION_of_GIRL=df.loc[df['CRIME HEAD']=='PROCURATION OF MINOR GILRS']
df_PROCURATION_of_GIRL

              STATE/UT                  CRIME HEAD  Total
266     ANDHRA PRADESH  PROCURATION OF MINOR GILRS    643
267  ARUNACHAL PRADESH  PROCURATION OF MINOR GILRS      0
268              ASSAM  PROCURATION OF MINOR GILRS    366
269              BIHAR  PROCURATION OF MINOR GILRS    845
270       CHHATTISGARH  PROCURATION OF MINOR GILRS     74
271                GOA  PROCURATION OF MINOR GILRS     37
272            GUJARAT  PROCURATION OF MINOR GILRS     71
273            HARYANA  PROCURATION OF MINOR GILRS      8
274   HIMACHAL PRADESH  PROCURATION OF MINOR GILRS     23
275    JAMMU & KASHMIR  PROCURATION OF MINOR GILRS      0
276          JHARKHAND  PROCURATION OF MINOR GILRS    250
277          KARNATAKA  PROCURATION OF MINOR GILRS     79
278             KERALA  PROCURATION OF MINOR GILRS    176
279     MADHYA PRADESH  PROCURATION OF MINOR GILRS    159
280        MAHARASHTRA  PROCURATION OF MINOR GILRS    390
281            MANIPUR  PROCURATION OF MINOR GILRS      0
282          MEGHALAYA  PROCURATION OF MINOR GILRS      3
283            MIZORAM  PROCURATION OF MINOR GILRS      0
284           NAGALAND  PROCURATION OF MINOR GILRS      0
285             ODISHA  PROCURATION OF MINOR GILRS     44
286             PUNJAB  PROCURATION OF MINOR GILRS     20
287          RAJASTHAN  PROCURATION OF MINOR GILRS     52
288             SIKKIM  PROCURATION OF MINOR GILRS      0
289         TAMIL NADU  PROCURATION OF MINOR GILRS     59
290            TRIPURA  PROCURATION OF MINOR GILRS     70
291      UTTAR PRADESH  PROCURATION OF MINOR GILRS    106
292        UTTARAKHAND  PROCURATION OF MINOR GILRS    132
293        WEST BENGAL  PROCURATION OF MINOR GILRS    853
294     TOTAL (STATES)  PROCURATION OF MINOR GILRS   4460
295      A & N ISLANDS  PROCURATION OF MINOR GILRS      0
296         CHANDIGARH  PROCURATION OF MINOR GILRS      0
297       D & N HAVELI  PROCURATION OF MINOR GILRS      0
298        DAMAN & DIU  PROCURATION OF MINOR GILRS      0
299              DELHI  PROCURATION OF MINOR GILRS     13
300        LAKSHADWEEP  PROCURATION OF MINOR GILRS      0
301         PUDUCHERRY  PROCURATION OF MINOR GILRS      0
302        TOTAL (UTs)  PROCURATION OF MINOR GILRS     13
303  TOTAL (ALL-INDIA)  PROCURATION OF MINOR GILRS   4473

In [19]:
df_SELLING_OF_GIRLS=df.loc[df['CRIME HEAD']=='SELLING OF GIRLS FOR PROSTITUTION']
df_SELLING_OF_GIRLS

              STATE/UT                         CRIME HEAD  Total
342     ANDHRA PRADESH  SELLING OF GIRLS FOR PROSTITUTION     76
343  ARUNACHAL PRADESH  SELLING OF GIRLS FOR PROSTITUTION      0
344              ASSAM  SELLING OF GIRLS FOR PROSTITUTION      7
345              BIHAR  SELLING OF GIRLS FOR PROSTITUTION     16
346       CHHATTISGARH  SELLING OF GIRLS FOR PROSTITUTION      4
347                GOA  SELLING OF GIRLS FOR PROSTITUTION      0
348            GUJARAT  SELLING OF GIRLS FOR PROSTITUTION      1
349            HARYANA  SELLING OF GIRLS FOR PROSTITUTION      9
350   HIMACHAL PRADESH  SELLING OF GIRLS FOR PROSTITUTION      1
351    JAMMU & KASHMIR  SELLING OF GIRLS FOR PROSTITUTION      0
352          JHARKHAND  SELLING OF GIRLS FOR PROSTITUTION     13
353          KARNATAKA  SELLING OF GIRLS FOR PROSTITUTION      1
354             KERALA  SELLING OF GIRLS FOR PROSTITUTION      0
355     MADHYA PRADESH  SELLING OF GIRLS FOR PROSTITUTION    281
356        MAHARASHTRA  SELLING OF GIRLS FOR PROSTITUTION     55
357            MANIPUR  SELLING OF GIRLS FOR PROSTITUTION      0
358          MEGHALAYA  SELLING OF GIRLS FOR PROSTITUTION      0
359            MIZORAM  SELLING OF GIRLS FOR PROSTITUTION      0
360           NAGALAND  SELLING OF GIRLS FOR PROSTITUTION      0
361             ODISHA  SELLING OF GIRLS FOR PROSTITUTION      0
362             PUNJAB  SELLING OF GIRLS FOR PROSTITUTION     12
363          RAJASTHAN  SELLING OF GIRLS FOR PROSTITUTION     13
364             SIKKIM  SELLING OF GIRLS FOR PROSTITUTION      0
365         TAMIL NADU  SELLING OF GIRLS FOR PROSTITUTION      0
366            TRIPURA  SELLING OF GIRLS FOR PROSTITUTION      0
367      UTTAR PRADESH  SELLING OF GIRLS FOR PROSTITUTION     48
368        UTTARAKHAND  SELLING OF GIRLS FOR PROSTITUTION      0
369        WEST BENGAL  SELLING OF GIRLS FOR PROSTITUTION    522
370     TOTAL (STATES)  SELLING OF GIRLS FOR PROSTITUTION   1059
371      A & N ISLANDS  SELLING OF GIRLS FOR PROSTITUTION      0
372         CHANDIGARH  SELLING OF GIRLS FOR PROSTITUTION      0
373       D & N HAVELI  SELLING OF GIRLS FOR PROSTITUTION      0
374        DAMAN & DIU  SELLING OF GIRLS FOR PROSTITUTION      0
375              DELHI  SELLING OF GIRLS FOR PROSTITUTION     15
376        LAKSHADWEEP  SELLING OF GIRLS FOR PROSTITUTION      0
377         PUDUCHERRY  SELLING OF GIRLS FOR PROSTITUTION      0
378        TOTAL (UTs)  SELLING OF GIRLS FOR PROSTITUTION     15
379  TOTAL (ALL-INDIA)  SELLING OF GIRLS FOR PROSTITUTION   1074

In [20]:
df_EXPOSURE_AND_ABANDONMENT  =df.loc[df['CRIME HEAD']=='EXPOSURE AND ABANDONMENT']
df_EXPOSURE_AND_ABANDONMENT

              STATE/UT                CRIME HEAD  Total
228     ANDHRA PRADESH  EXPOSURE AND ABANDONMENT    208
229  ARUNACHAL PRADESH  EXPOSURE AND ABANDONMENT      0
230              ASSAM  EXPOSURE AND ABANDONMENT      0
231              BIHAR  EXPOSURE AND ABANDONMENT      9
232       CHHATTISGARH  EXPOSURE AND ABANDONMENT     71
233                GOA  EXPOSURE AND ABANDONMENT     12
234            GUJARAT  EXPOSURE AND ABANDONMENT    158
235            HARYANA  EXPOSURE AND ABANDONMENT     35
236   HIMACHAL PRADESH  EXPOSURE AND ABANDONMENT     24
237    JAMMU & KASHMIR  EXPOSURE AND ABANDONMENT      5
238          JHARKHAND  EXPOSURE AND ABANDONMENT     10
239          KARNATAKA  EXPOSURE AND ABANDONMENT     10
240             KERALA  EXPOSURE AND ABANDONMENT     46
241     MADHYA PRADESH  EXPOSURE AND ABANDONMENT    196
242        MAHARASHTRA  EXPOSURE AND ABANDONMENT    836
243            MANIPUR  EXPOSURE AND ABANDONMENT      0
244          MEGHALAYA  EXPOSURE AND ABANDONMENT      0
245            MIZORAM  EXPOSURE AND ABANDONMENT      1
246           NAGALAND  EXPOSURE AND ABANDONMENT      0
247             ODISHA  EXPOSURE AND ABANDONMENT      0
248             PUNJAB  EXPOSURE AND ABANDONMENT     14
249          RAJASTHAN  EXPOSURE AND ABANDONMENT    121
250             SIKKIM  EXPOSURE AND ABANDONMENT      1
251         TAMIL NADU  EXPOSURE AND ABANDONMENT     16
252            TRIPURA  EXPOSURE AND ABANDONMENT      0
253      UTTAR PRADESH  EXPOSURE AND ABANDONMENT      2
254        UTTARAKHAND  EXPOSURE AND ABANDONMENT      0
255        WEST BENGAL  EXPOSURE AND ABANDONMENT     12
256     TOTAL (STATES)  EXPOSURE AND ABANDONMENT   1787
257      A & N ISLANDS  EXPOSURE AND ABANDONMENT      2
258         CHANDIGARH  EXPOSURE AND ABANDONMENT     29
259       D & N HAVELI  EXPOSURE AND ABANDONMENT      0
260        DAMAN & DIU  EXPOSURE AND ABANDONMENT      0
261              DELHI  EXPOSURE AND ABANDONMENT     40
262        LAKSHADWEEP  EXPOSURE AND ABANDONMENT      0
263         PUDUCHERRY  EXPOSURE AND ABANDONMENT      1
264        TOTAL (UTs)  EXPOSURE AND ABANDONMENT     72
265  TOTAL (ALL-INDIA)  EXPOSURE AND ABANDONMENT   1859